# GET http://127.0.0.1:8000/api/v1/candidates/?profession=player-claim-agree&town=Moscow
GET http://127.0.0.1:8000/api/v1/candidates/
# GET http://127.0.0.1:8000/api/v1/candidates/?grade=junior
# POST http://127.0.0.1:8000/api/v1/users/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzAwOTI3MjI5LCJpYXQiOjE2OTgzMzUyMjksImp0aSI6IjYzNzliYjQwMjQ3YTRmNTk5MzJjYjIxOGQ5YTU4Y2JlIiwidXNlcl9pZCI6MX0.L2DFZK4IRJ53EcKlQxeG_Vzng6CSGUuq3jkYsglY86I

# {
#     "email": "1frost3jlf@gmail.com",
#     "username": "username123",
#     "password": "fsjfojosjffjsf"
# }
