# Generated by Django 4.2.6 on 2023-10-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="town",
            name="city",
            field=models.CharField(
                max_length=50, verbose_name="Название города"
            ),
        ),
        migrations.AlterField(
            model_name="town",
            name="district",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Округ"
            ),
        ),
        migrations.AlterField(
            model_name="town",
            name="region",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Область, регион"
            ),
        ),
    ]
