# Generated by Django 4.2.6 on 2023-10-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0002_region_distinct_optional"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название формата"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
            ],
            options={
                "verbose_name": "Формат работы",
                "verbose_name_plural": "Форматы работ",
                "ordering": ("id",),
            },
        ),
        migrations.AddField(
            model_name="candidate",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата создания кандидата"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="candidate",
            name="photo",
            field=models.ImageField(
                blank=True, upload_to="media/", verbose_name="Фото кандидата"
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="employment",
            field=models.ManyToManyField(
                related_name="candidate",
                to="candidate.employment",
                verbose_name="Формат работы",
            ),
        ),
    ]
