# Generated by Django 4.2.6 on 2023-10-25 06:23

import candidate.models
import candidate.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "candidate",
            "0003_employment_candidate_created_date_candidate_photo_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="experience",
            field=models.CharField(
                choices=[
                    ("Нет опыта", "no"),
                    ("1 - 3 года", "one"),
                    ("3 - 6 лет", "three"),
                ],
                default=candidate.models.ExperienceTitle["no"],
                max_length=16,
                verbose_name="Коммерческий опыт",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="first_name",
            field=models.CharField(default="", max_length=150, verbose_name="Имя"),
        ),
        migrations.AddField(
            model_name="candidate",
            name="last_name",
            field=models.CharField(default="", max_length=150, verbose_name="Фамилия"),
        ),
        migrations.AddField(
            model_name="candidate",
            name="portfolio",
            field=models.URLField(default=None, unique=True, verbose_name="Портфолио"),
        ),
        migrations.AddField(
            model_name="candidate",
            name="project",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Укажите количество не учебных(pet) проектов",
                validators=[django.core.validators.MaxValueValidator(50)],
                verbose_name="Не учебные/pet проекты",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="resume",
            field=models.FileField(
                default=None,
                upload_to="C:\\Dev\\hackathon\\Bridge\\backend\\media",
                validators=[candidate.validators.validate_file_extension],
                verbose_name="Резюме",
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="reviews",
            field=models.URLField(
                blank=True, default=None, verbose_name="Отзывы менторов"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="photo",
            field=models.ImageField(
                blank=True,
                upload_to="C:\\Dev\\hackathon\\Bridge\\backend\\media",
                verbose_name="Фото кандидата",
            ),
        ),
    ]
