# Generated by Django 4.2.6 on 2023-10-26 15:15

import candidate.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0004_candidate_experience_candidate_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profession",
            name="slug",
            field=models.SlugField(default=1, unique=True, verbose_name="Slug"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="candidate",
            name="photo",
            field=models.ImageField(
                blank=True, upload_to="photo/", verbose_name="Фото кандидата"
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="resume",
            field=models.FileField(
                default=None,
                upload_to="resumes/",
                validators=[candidate.validators.validate_file_extension],
                verbose_name="Резюме",
            ),
        ),
    ]
