# Generated by Django 4.2.6 on 2023-10-27 08:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0005_profession_slug_alter_candidate_photo_and_more"),
        ("candidate", "0006_candidate_technology_alter_candidate_experience_and_more"),
    ]

    operations = []
