# Generated by Django 4.2.6 on 2023-10-27 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("candidate", "0006_candidate_technology_alter_candidate_experience_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Новая вакансия",
                        max_length=256,
                        verbose_name="Название вакансии",
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        default="ООО Рога и копыта",
                        max_length=256,
                        verbose_name="Название компании",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="Россия", max_length=256, verbose_name="Страна"
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        choices=[
                            ("high", "Высшее"),
                            ("high_profile", "Высшее профильное"),
                            ("no_matter", "Не важно"),
                            ("secondary_professional", "Средне-техническое"),
                        ],
                        default="high_profile",
                        max_length=50,
                        verbose_name="Образование",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания вакансии"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активная"),
                            ("not_active", "Не активная"),
                            ("archived", "Архивная"),
                            ("hidden", "Скрытая"),
                        ],
                        default="active",
                        max_length=16,
                        verbose_name="Статус вакансии",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[("junior", "Junior"), ("middle", "Middle")],
                        default="junior",
                        max_length=16,
                        verbose_name="Грейд",
                    ),
                ),
                (
                    "experience",
                    models.CharField(
                        choices=[
                            ("no", "Нет опыта"),
                            ("one", "1 - 3 года"),
                            ("three", "3 - 6 лет"),
                        ],
                        default="no",
                        max_length=16,
                        verbose_name="Коммерческий опыт",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Добавьте условия вакансии",
                        max_length=4000,
                        verbose_name="Описание вакансии",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancy",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор вакансии",
                    ),
                ),
                (
                    "employment",
                    models.ManyToManyField(
                        related_name="vacancy",
                        to="candidate.employment",
                        verbose_name="Формат работы",
                    ),
                ),
                (
                    "profession",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="vacancy",
                        to="candidate.profession",
                        verbose_name="Профессия",
                    ),
                ),
                (
                    "technology",
                    models.ManyToManyField(
                        related_name="vacancy",
                        to="candidate.technology",
                        verbose_name="Стек технологий",
                    ),
                ),
                (
                    "town",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="vacancy",
                        to="candidate.town",
                        verbose_name="Город",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вакансия",
                "verbose_name_plural": "Вакансии",
            },
        ),
    ]
