# Generated by Django 4.2.6 on 2023-10-27 04:10

import candidate.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("candidate", "0005_alter_candidate_photo_alter_candidate_resume"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Новая вакансия",
                        max_length=256,
                        verbose_name="Название вакансии",
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        default="ООО Рога и копыта",
                        max_length=256,
                        verbose_name="Название компании",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="Россия", max_length=256, verbose_name="Страна"
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        choices=[
                            ("h", "Высшее"),
                            ("hp", "Высшее профильное"),
                            ("nm", "Не важно"),
                            ("sp", "Средне-техническое"),
                        ],
                        default="hp",
                        verbose_name="Образование",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания вакансии"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Активная", "Active"),
                            ("Не активная", "Not Active"),
                            ("Архивная", "Archived"),
                            ("Скрытая", "Hidden"),
                        ],
                        default="Активная",
                        verbose_name="Статус вакансии",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[("Junior", "junior"), ("Middle", "middle")],
                        default=candidate.models.GradeName["junior"],
                        max_length=16,
                        verbose_name="Грейд",
                    ),
                ),
                (
                    "experience",
                    models.CharField(
                        choices=[
                            ("Нет опыта", "no"),
                            ("1 - 3 года", "one"),
                            ("3 - 6 лет", "three"),
                        ],
                        default=candidate.models.ExperienceTitle["no"],
                        max_length=16,
                        verbose_name="Коммерческий опыт",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Добавьте условия вакансии",
                        verbose_name="Описание вакансии",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancy",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор вакансии",
                    ),
                ),
                (
                    "employment",
                    models.ManyToManyField(
                        related_name="vacancy",
                        to="candidate.employment",
                        verbose_name="Формат работы",
                    ),
                ),
                (
                    "profession",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="vacancy",
                        to="candidate.profession",
                        verbose_name="Профессия",
                    ),
                ),
                (
                    "town",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="vacancy",
                        to="candidate.town",
                        verbose_name="Город",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вакансия",
                "verbose_name_plural": "Вакансии",
            },
        ),
    ]
