# Generated by Django 4.2.6 on 2023-10-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidate", "0006_candidate_technology_alter_candidate_experience_and_more"),
        ("vacancy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="technology",
            field=models.ManyToManyField(
                related_name="vacancy",
                to="candidate.technology",
                verbose_name="Стек технологий",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="experience",
            field=models.CharField(
                choices=[
                    ("no", "Нет опыта"),
                    ("one", "1 - 3 года"),
                    ("three", "3 - 6 лет"),
                ],
                default="no",
                max_length=16,
                verbose_name="Коммерческий опыт",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="grade",
            field=models.CharField(
                choices=[("jun", "Junior"), ("mdl", "Middle")],
                default="jun",
                max_length=16,
                verbose_name="Грейд",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="status",
            field=models.CharField(
                choices=[
                    ("act", "Активная"),
                    ("nact", "Не активная"),
                    ("arc", "Архивная"),
                    ("hid", "Скрытая"),
                ],
                default="act",
                verbose_name="Статус вакансии",
            ),
        ),
    ]
