services:
  postgres-db:
    image: postgres:13.0-alpine
    container_name: postgres-container-randomcoffee
    env_file:
      - ../../.env
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
