name: Run container

on: 
  workflow_dispatch:

jobs: 
  Run:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker container ls --all
            sudo docker container rm postgres_bridge
            sudo docker compose up -d
            sudo docker container ls --all
            sudo docker container start -a postgres_bridge            
